leanguaje: node_js

cache:
  directories:
    -node_modules
    - ~/.npm

node_js:
  - '12'
  git:
    depth: 3

script:
  - yarn build

deploy:
  provider: pages
  skip-clean: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/
  target-branch: gh-page
  commit-message: "Deploy del Proyecto"
  on:
    branch: master
